import Head from "next/head";
import { Inter } from "next/font/google";
import Layout from "@/components/Layout";
import AnimatedText from "@/components/AnimatedText";
import HireMe from "@/components/HireMe";
import Image from "next/image";
import profilePic from "../../public/images/code.png";
import Link from "next/link";
import { LinkArrow } from "@/components/Icon";
import TransitionEffect from "@/components/TransitionEffect";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center justify-center text-dark w-full min-h-screen ">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-start justify-between w-full lg:flex-col lg:items-center lg:space-y-6">
            {/* Image Section */}
            <div className="w-1/2 flex justify-center md:w-full md:mb-4">
              <Image
                src={profilePic}
                alt="Zi Ying Heng"
                className="w-full h-auto lg:hidden md:inline-block md:w-48 sm:w-32"
              />
            </div>

            {/* Description Section */}
            <div className="w-1/2 flex flex-col items-start lg:w-full lg:items-center lg:text-center">
              <AnimatedText
                text="Hi, I am Zi Ying"
                className="!text-6xl !text-left xl:!text5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                Recent Computer Science graduate from Monash University Malaysia
                with a CGPA of 3.8, proficient in Python and Java. Eager to
                apply my skills in a full-time role and contribute to impactful
                projects while continuing to grow professionally.
              </p>
              <div className="flex items-center mt-2 space-x-4 lg:self-center">
                {" "}
                {/* Space between buttons */}
                <Link
                  href="/ZY-resume.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text.lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-trasnparent hover:border-dark md:p-2 md:px-4 md:text-base"
                  download={true}
                >
                  Resume
                  <LinkArrow className="w-6 ml-1" />
                </Link>
                <Link
                  href="/contact" // Link to the contact page
                  className="text-lg font-medium capitalize text-dark underline md:text-base"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
      </main>
    </>
  );
}
